from typing import Optional,List
from moval.domain.enums import Role, ShipmentStatus
from datetime import datetime, timezone

class UserRepo:
        def get_by_email(self, email: str): ...
        def exists_email(self, email: str) -> bool: ...

class SessionRepo:
        def create_session(self, user_id: int) -> str: ...

class ShipmentRepo:
        def list_pending(self) -> List[dict]: ...
        def get(self, shipment_id: int) -> dict | None: ...
        def assign(self, shipment_id: list[int], courier_id: int) -> None: ...
        def unassign(self, shipment_id: int) -> None: ...
        def update(self, shipment_id: int, fields: dict) -> None: ...
        def set_status(self, shipment_id: int, status: ShipmentStatus) -> None: ...

class CourierRepo:
        def list_available(self) -> List[dict]: ...
        def can_take_more(self, courier_id: int, limit: int) -> bool: ...

class RatingRepo:
        def create_delivery_rating(self, shipment_id: int, customer_id: int, courier_id: int, score: int, comment: str | None): ...
        def recalc_courier_avg(self, courier_id: int) -> None: ...
        def has_rating_for_shipment(self, shipment_id: int, customer_id: int) -> bool: ...

class IncidentRepo:
        def create_incident(self, shipment_id: int, reported_id: int, description: str): ...

class HelpRepo:
        def load_help_content(self) -> str: ...

class WorkdayRepo:
        def get_active_workday(self, courier_id: int) -> dict | None: ...
        def create_workday(self, courier_id: int, start_ts) -> dict: ...
        def close_workday(self, workday_id: int, end_ts) -> dict: ...

