from typing import Optional,List
from moval.domain.enums import Role, ShipmentStatus
from datetime import datetime, timezone

class UserRepo:
        def get_by_email(self, email: str): ...
        def exists_email(self, email: str) -> bool: ...

class SessionRepo:
        def create_session(self, user_id: int) -> str: ...

class ShipmentRepo:
        def list_pending(self) -> List[dict]: ...
        def get(self, shipment_id: int) -> dict | None: ...
        def assign(self, shipment_id: list[int], courier_id: int) -> None: ...
        def unassign(self, shipment_id: int) -> None: ...
        def update(self, shipment_id: int, fields: dict) -> None: ...
        def set_status(self, shipment_id: int, status: ShipmentStatus, delivered_at: datetime | None = None) -> None: ...
        def list_all(self, filters:dict | None = None) -> List[dict]: ...
        def list_by_courier(self, courier_id: int, filters: dict | None = None) -> List[dict]: ...
        def list_by_customer(self, customer_id: int, filters: dict | None = None) -> List[dict]: ...
        def count_by_courier(self, courier_id: int, filters: dict | None = None) -> int: ...


class CourierRepo:
        def list_available(self) -> List[dict]: ...
        def can_take_more(self, courier_id: int, limit: int) -> bool: ...
        def get(self, courier_id: int) -> dict | None: ...


class RatingRepo:
        def create_delivery_rating(self, shipment_id: int, customer_id: int, courier_id: int, score: int, comment: str | None): ...
        def recalc_courier_avg(self, courier_id: int) -> None: ...
        def has_rating_for_shipment(self, shipment_id: int, customer_id: int) -> bool: ...
        def average_by_courier(self, courier_id: int) -> float | None: ...
        def has_rating_for_workday(self, workday_id: int, customer_id: int) -> bool: ...
        def create_workday_rating(self, workday_id: int, customer_id: int, courier_id: int, score: int, comment: str | None, created_at=None) -> dict: ...



class IncidentRepo:
        def create_incident(self, shipment_id: int, reported_id: int, description: str): ...

class HelpRepo:
        def load_help_content(self) -> str: ...

class WorkdayRepo:
        def get_active_workday(self, courier_id: int) -> dict | None: ...
        def create_workday(self, courier_id: int, start_ts) -> dict: ...
        def close_workday(self, workday_id: int, end_ts) -> dict: ...
        def get_by_id(self, workday_id: int) -> dict | None: ...

