from .login_view import LoginView
from .register_view import RegisterView
from .admin_view import AdminView
from .courier_view import CourierView
from .customer_view import CustomerView
from .profile_dialog import ProfileDialog
from .help_dialog import HelpDialog
from .options_dialog import OptionsDialog
from .shipment_dialog import ShipmentDialog
from .rating_dialog import VentanaValoracion
from .incident_dialog import VentanaIncidencia
from .notification_dialog import NotificationDialog